# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authenticator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Authenticator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x41uthenticator.proto\"7\n\x0cPublicRSAKey\x12\t\n\x01n\x18\x01 \x01(\x0c\x12\t\n\x01\x65\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\"7\n\x06\x41\x45SKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\"\x8a\x01\n\x14\x41uthenticatorMessage\x12\x30\n\x13\x61uthentication_step\x18\x01 \x01(\x0e\x32\x13.AuthenticationStep\x12\"\n\x0bnew_rsa_key\x18\x02 \x01(\x0b\x32\r.PublicRSAKey\x12\x1c\n\x0bnew_aes_key\x18\x03 \x01(\x0b\x32\x07.AESKey*Q\n\x12\x41uthenticationStep\x12\x0f\n\x0bNEW_SESSION\x10\x00\x12\x0b\n\x07NEW_RSA\x10\x01\x12\x0b\n\x07NEW_AES\x10\x02\x12\x10\n\x0c\x43ONFIRMATION\x10\x03\x62\x06proto3'
)

_AUTHENTICATIONSTEP = _descriptor.EnumDescriptor(
  name='AuthenticationStep',
  full_name='AuthenticationStep',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW_SESSION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW_RSA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEW_AES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIRMATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=359,
)
_sym_db.RegisterEnumDescriptor(_AUTHENTICATIONSTEP)

AuthenticationStep = enum_type_wrapper.EnumTypeWrapper(_AUTHENTICATIONSTEP)
NEW_SESSION = 0
NEW_RSA = 1
NEW_AES = 2
CONFIRMATION = 3



_PUBLICRSAKEY = _descriptor.Descriptor(
  name='PublicRSAKey',
  full_name='PublicRSAKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='PublicRSAKey.n', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='PublicRSAKey.e', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PublicRSAKey.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=78,
)


_AESKEY = _descriptor.Descriptor(
  name='AESKey',
  full_name='AESKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AESKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='AESKey.nonce', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AESKey.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=135,
)


_AUTHENTICATORMESSAGE = _descriptor.Descriptor(
  name='AuthenticatorMessage',
  full_name='AuthenticatorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authentication_step', full_name='AuthenticatorMessage.authentication_step', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_rsa_key', full_name='AuthenticatorMessage.new_rsa_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_aes_key', full_name='AuthenticatorMessage.new_aes_key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=276,
)

_AUTHENTICATORMESSAGE.fields_by_name['authentication_step'].enum_type = _AUTHENTICATIONSTEP
_AUTHENTICATORMESSAGE.fields_by_name['new_rsa_key'].message_type = _PUBLICRSAKEY
_AUTHENTICATORMESSAGE.fields_by_name['new_aes_key'].message_type = _AESKEY
DESCRIPTOR.message_types_by_name['PublicRSAKey'] = _PUBLICRSAKEY
DESCRIPTOR.message_types_by_name['AESKey'] = _AESKEY
DESCRIPTOR.message_types_by_name['AuthenticatorMessage'] = _AUTHENTICATORMESSAGE
DESCRIPTOR.enum_types_by_name['AuthenticationStep'] = _AUTHENTICATIONSTEP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicRSAKey = _reflection.GeneratedProtocolMessageType('PublicRSAKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICRSAKEY,
  '__module__' : 'Authenticator_pb2'
  # @@protoc_insertion_point(class_scope:PublicRSAKey)
  })
_sym_db.RegisterMessage(PublicRSAKey)

AESKey = _reflection.GeneratedProtocolMessageType('AESKey', (_message.Message,), {
  'DESCRIPTOR' : _AESKEY,
  '__module__' : 'Authenticator_pb2'
  # @@protoc_insertion_point(class_scope:AESKey)
  })
_sym_db.RegisterMessage(AESKey)

AuthenticatorMessage = _reflection.GeneratedProtocolMessageType('AuthenticatorMessage', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATORMESSAGE,
  '__module__' : 'Authenticator_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticatorMessage)
  })
_sym_db.RegisterMessage(AuthenticatorMessage)


# @@protoc_insertion_point(module_scope)
