# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Base.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nBase.proto\"1\n\x06RSAKey\x12\t\n\x01n\x18\x01 \x01(\x0c\x12\t\n\x01\x65\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\"7\n\x06\x41\x45SKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x02*2\n\x0e\x45ncryptionType\x12\x0e\n\nPLAIN_TEXT\x10\x00\x12\x07\n\x03RSA\x10\x01\x12\x07\n\x03\x41\x45S\x10\x02\x62\x06proto3'
)

_ENCRYPTIONTYPE = _descriptor.EnumDescriptor(
  name='EncryptionType',
  full_name='EncryptionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLAIN_TEXT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RSA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=122,
  serialized_end=172,
)
_sym_db.RegisterEnumDescriptor(_ENCRYPTIONTYPE)

EncryptionType = enum_type_wrapper.EnumTypeWrapper(_ENCRYPTIONTYPE)
PLAIN_TEXT = 0
RSA = 1
AES = 2



_RSAKEY = _descriptor.Descriptor(
  name='RSAKey',
  full_name='RSAKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='RSAKey.n', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='RSAKey.e', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RSAKey.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=63,
)


_AESKEY = _descriptor.Descriptor(
  name='AESKey',
  full_name='AESKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AESKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='AESKey.nonce', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AESKey.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['RSAKey'] = _RSAKEY
DESCRIPTOR.message_types_by_name['AESKey'] = _AESKEY
DESCRIPTOR.enum_types_by_name['EncryptionType'] = _ENCRYPTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RSAKey = _reflection.GeneratedProtocolMessageType('RSAKey', (_message.Message,), {
  'DESCRIPTOR' : _RSAKEY,
  '__module__' : 'Base_pb2'
  # @@protoc_insertion_point(class_scope:RSAKey)
  })
_sym_db.RegisterMessage(RSAKey)

AESKey = _reflection.GeneratedProtocolMessageType('AESKey', (_message.Message,), {
  'DESCRIPTOR' : _AESKEY,
  '__module__' : 'Base_pb2'
  # @@protoc_insertion_point(class_scope:AESKey)
  })
_sym_db.RegisterMessage(AESKey)


# @@protoc_insertion_point(module_scope)
